version: 2

sources:
  - name: signals
    database: signals
    schema: raw
    description: "Signal data landing place"
    tables:
      - name: event

models:
  - name: fct_event
    description: "Fact table for an event"
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: user_id
        description: ""
        data_tests:
          - not_null
          # - relationships:
          #   to: ref('dim_user_t')
          #   field: id
  
  - name: dim_user_t
    description: "Contains all the user table information"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null